# Welcome to Sikka!

# --- Required options --- #

# Name of website
title: Sikka

# Your name to show in the footer
author: Sikka

# --- List of links in the navigation bar --- #

navbar-links:
  Projects: "projects"
  Networks: "networks"
  Community: "community"
  About: "about"


# --- Footer social media links --- #

social-network-links:
  email: "someone@example.com"
  twitter: daattali
  telegram: yourname
  keybase: yourname

# --- About team user media links --- #
about-team-links:
  email: "someone@example.com"
  twitter: daattali
  keybase: yourname
  gitHub: daattali
  linkedin: daattali
  webpage: url



